### ISSUE TITLE
get http://arxivsearch.mathweb.org demo working again

### ISSUE THREAD

**Issue by kohlhase** [KWARC/mws#104]
We have a demo at the URI above, and it does not work any more. There are two problems, it seems that that LaTeXML daemon is down @tkw1536 can probbably help with this and the temasearch daemon on jupiter seems dead. @alexglont hat problems getting tthis to run again. This is the main problem.

**Comment by kohlhase** [comment]
@tkw1536 found the problem with the LaTeXML daemon, it is on opal, which he is trying to restart at the moment.

**Comment by tkw1536** [comment]
opal is now back up and running

**Comment by kohlhase** [comment]
OK, so now it is really only TEMA-search's fault.

**Comment by a-hambasan** [comment]
The http://arxivsearch.mathweb.org demo is working again.

**Comment by kohlhase** [comment]
Wow, thanks. What was the problem? Could you do a quick post-mortem?

**Comment by a-hambasan** [comment]
Elastic Search was not properly configured.
