### ISSUE TITLE
Hash sum mismatch

### ISSUE THREAD

**Issue by physikerwelt** [KWARC/mws#92]
I got a problem updating my ubuntu packages via
apt-get update
```
Ign http://nova.clouds.archive.ubuntu.com trusty/universe Translation-en_US.UTF-8
Fetched 220 kB in 2s (84.4 kB/s)
W: Failed to fetch http://nova.clouds.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
@Raduh Can you imagine any activity on your end that might be related to this issue. Otherwise just close the bug.

**Comment by Raduh** [comment]
No. Also, the failed-to-fetch URL doesn't seem related to the MWS PPA.

**Comment by physikerwelt** [comment]
However, I was just wondering since removing
/etc/apt/sources.list.d/radu-hambasan-math-web-search-trusty.list
fixed the problem.

**Comment by Raduh** [comment]
Interesting. Not sure why -- I have not updated the PPA recently.
