### ISSUE TITLE
do we stem the words for ES while harvesting and in the query

### ISSUE THREAD

**Issue by kohlhase** [KWARC/mws#99]
or does ES do that itself? Concretely, do we find "arithmetic progressions"  and "arithmetical progression" when looking for "arithmetic progression"?

**Comment by kohlhase** [comment]
I think this is still an issue.

**Comment by kohlhase** [comment]
actually, this is primarily a question, if I know the answer, then we can decide what we want to do.

**Comment by a-hambasan** [comment]
Elasticsearch's analyzer doesn't do stemming by default. If we want to stem the words, we have to set it accordingly (which we didn't). So no, at the moment, ES doesn't stem the words.

**Comment by kohlhase** [comment]
thanks.
